Add kdesrc-build things to the zshrc file

diff --git a/roles/base_configs/templates/zshrc.j2 b/roles/base_configs/templates/zshrc.j2
--- a/roles/base_configs/templates/zshrc.j2
+++ b/roles/base_configs/templates/zshrc.j2
@@ -208,3 +208,39 @@ export FZF_DEFAULT_OPTS='--height 40% --reverse --border'
 
 # And at the end display today's tasks
 print_today_tasks
+# kdesrc-build #################################################################
+
+## Add kdesrc-build to PATH
+export PATH="$HOME/dev/kde/src/kdesrc-build:$PATH"
+
+## Autocomplete for kdesrc-run
+function _comp-kdesrc-run
+{
+  local cur
+  COMPREPLY=()
+  cur="${COMP_WORDS[COMP_CWORD]}"
+
+  # Complete only the first argument
+  if [[ $COMP_CWORD != 1 ]]; then
+    return 0
+  fi
+
+  # Retrieve build modules through kdesrc-run
+  # If the exit status indicates failure, set the wordlist empty to avoid
+  # unrelated messages.
+  local modules
+  if ! modules=$(kdesrc-run --list-installed);
+  then
+      modules=""
+  fi
+
+  # Return completions that match the current word
+  COMPREPLY=( $(compgen -W "${modules}" -- "$cur") )
+
+  return 0
+}
+
+## Register autocomplete function
+complete -o nospace -F _comp-kdesrc-run kdesrc-run
+
+################################################################################
